import { apartment1, apartment2, apartment3, apartment4, apartment5, apartment6 } from "./apartmentImages"

export const propertyList = [
    {
        id: 1,
        src: apartment1,
        name: "Stylist apartment in center of the city",
        bedCount: 4,
        roomType: "Entire apartment",
        rating: 3.8,
        superHost: true,
        location: "Finland",
        city: "Helsinki"
    },
    {
        id: 1.5,
        src: apartment1,
        name: "Stylist apartment in center of the city",
        bedCount: 4,
        roomType: "Entire apartment",
        rating: 3.8,
        superHost: true,
        location: "Finland",
        city: "Helsinki"
    },
    {
        id: 2,
        src: apartment2,
        name: "Cozy, peaceful and private room",
        roomType: "Private room",
        bedCount: 1,
        rating: 4.65,
        superHost: false,
        state: "Finland",
        city: "Helsinki"
    },
    {
        id: 2.5,
        src: apartment2,
        name: "Cozy, peaceful and private room",
        roomType: "Private room",
        bedCount: 1,
        rating: 4.65,
        superHost: false,
        state: "Finland",
        city: "Helsinki"
    },
    {
        id: 3,
        src: apartment3,
        name: "Modern House in remote area",
        roomType: "Entire House",
        bedCount: 1,
        rating: 4.7,
        superHost: false,
        state: "Finland",
        city: "Helsinki"
    },
    {   
        id: 4,
        src: apartment4,
        name: "Stylist room in design district",
        bedCount: 3,
        roomType: "Entire apartment",
        rating: 4.2,
        superHost: true,
        city: "Turku",
        state: "Finland",
    },
    {
        id: 5,
        src: apartment5,
        name: "Modern apartment close tto nature",
        roomType: "Private room",
        bedCount: 4,
        rating: 5,
        superHost: false,
        state: "Finland",
        city: "Vaasa"
    },
    {
        id: 6,
        src: apartment6,
        name: "House in remote area",
        roomType: "Entire House",
        bedCount: 1,
        rating: 4.78,
        superHost: false,
        state: "Finland",
        city: "Helsinki"
    },
    {
        id: 7,
        src: apartment1,
        name: "House in the Center",
        roomType: "Entire House",
        bedCount: 6,
        rating: 3.3,
        superHost: true,
        state: "Finland",
        city: "Oulu",
    },
    {
        id: 8,
        src: apartment3,
        name: "House in the Center",
        roomType: "Entire House",
        bedCount: 1,
        rating: 1,
        superHost: true,
        state: "Finland",
        city: "Oulu",
    },
    {
        id: 8.5,
        src: apartment5,
        name: "House in the Center",
        roomType: "Entire House",
        bedCount: 3,
        rating: 1,
        superHost: true,
        state: "Finland",
        city: "Oulu",
    },
    {
        id: 9,
        src: apartment5,
        name: "House in the Center",
        roomType: "Entire House",
        bedCount: 3,
        rating: 4,
        superHost: true,
        state: "Finland",
        city: "Oulu",
    }
]